### ISSUE TITLE
Yocto3D accelerometer sometimes produces bogus readings

### ISSUE THREAD

**Issue by teichman** [yoctopuce/yoctolib_cpp#15]
Hi,

I'm having some problems with the Yocto3D.  I slightly modified the main.cpp for the example code to print out x, y, and z values for the accelerometer and am getting incorrect output.  This happens more or less randomly, and whether it works or not seems to be determined at the time the USB cable is connected.  That is, if it is working, I can stop and restart the program and everything will continue to work, but if it is producing incorrect output, stopping and restarting the program won't help.

I've seen this on both a 64bit laptop and a 32bit ARM machine, both running Ubuntu 14.04.

This is the output I'm getting for the x, y, and z acceleration values:

```
teichman@silicon:~/Desktop/yocto$ Examples/Doc-GettingStarted-Yocto-3D/Binary_Linux/64bits/demo any
tilt1
tilt2
compass acc     gyro
 -23.984        -23.964 -23.587 
 -23.984        -23.964 -23.587 
 -23.984        -23.964 -23.587 
 -23.984        -23.964 -23.587 
 -23.984        -23.964 -23.587 
 -23.984        -23.964 -23.587 
 -23.984        -23.964 -23.587 
 -23.984        -23.964 -23.587 
```

**Comment by yoctopuce** [comment]
Do you have resolved this issue?
