### ISSUE TITLE
YPwmInput::set_pulseCounter() does not work.

### ISSUE THREAD

**Issue by rk-bp** [yoctopuce/yoctolib_cpp#21]
YPwmInput::set_pulseCounter(10000) does not work in version of released on 1/13/2017.

"GET /api/pwmInput2/pulseCounter?pulseCounter=100000&. \r\n\r\n"

**Comment by yoctopuce** [comment]
It's not as issue of the C++ library but a limitation in the firmware of the Yocto-PWM-RX.
Originally, the set_pulseCounter function was only design to reset the counter, so the function
discarded value different of zero.

 We have fixed this bug in the firmware v26535 which work now as expected.

 The firmware is available on our web site:
	http://www.yoctopuce.com/EN/products/usb-electrical-interfaces/yocto-pwm-rx

**Comment by rk-bp** [comment]
Thanks for the quick fix.  I upgraded to the latest firmware and the set_pulseCounter function can now set values other than zero.
