### ISSUE TITLE
Select the sensor fusion mode

### ISSUE THREAD

**Issue by boilerbots** [yoctopuce/yoctolib_cpp#26]
I am asking if we could select the fusion mode as described in the BNO055 document section 3.3.3. I don't want absolute orientation because I am operating in an area with a lots of metal and high power electrical circuits. With the magnetometer feeding into the estimation this will basically be useless to me. Maybe you can expose a way to select among the 5 fusion methods?

I am creating this ticket so I know when this feature has been implemented. I feel this is pretty fundamental to the BNO055 and other could benefit from this.

**Comment by yoctopuce** [comment]
This feature has actually been implemented and is under testing right now. If you can send a mail to support at yoctopuce dot com, we will be happy to provide you the test firmware.
