### ISSUE TITLE
Types in yocto_api.h are missing a virtual destructor

### ISSUE THREAD

**Issue by aharrison24** [yoctopuce/yoctolib_cpp#29]
Many classes in yocto_api.h have `virtual` methods, but no `virtual` destructor. If they are used
polymorphically then this could result in undefined behaviour. See https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-dtor-virtual for discussion of the issue.

As an example, the `YMeasure` class does not have a `virtual` destructor.
https://github.com/yoctopuce/yoctolib_cpp/blob/42b0c45496ebecf3858caae9143e0acca50bfcb8/Sources/yocto_api.h#L1372

**Comment by yoctopuce** [comment]
That's funny! We have fixed that few days ago, but it has not yet been released.
We are validating other change that we maid to the lib, and we should publish this
fix next week.
