### ISSUE TITLE
CMAKE install directory

### ISSUE THREAD

**Issue by peppedxAlto** [yoctopuce/yoctolib_cpp#36]
Why are you disallowing me to choose my installation prefix?

```
if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
SET(CMAKE_INSTALL_PREFIX "/usr")
endif()

```

**Comment by srinsoz** [comment]
We have set this variable to support debian based distribution. But I understand that
can be annoying to prevent the user to specify the destination. Does remove these tree
lines solve your issue?

**Comment by peppedxAlto** [comment]
Hi,
Yes it does, but honestly I think this goes against the base expectation of cmake users.

Also I'd suggest for the cmake file to live in the root directory and add the installation targets so as to ease consuming the package using Cmake FetchContent extension.

Anyway thank you for the support.

**Comment by peppedxAlto** [comment]
I haven't been entirely correct, installation targets are there but ".cmake" files could be generated ( https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-packages ).

**Comment by srinsoz** [comment]
I think the following would work for everybody.
```
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT AND ${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
SET(CMAKE_INSTALL_PREFIX "/usr")
endif()
```
See more information  on CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT  : https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT.html

**Comment by peppedxAlto** [comment]
Yep,
for sure it works for me.

**Comment by srinsoz** [comment]
We have just released the fix.
