### ISSUE TITLE
Crash on initialization (yapiInitAPI)

### ISSUE THREAD

**Issue by gppaille-vyv** [yoctopuce/yoctolib_cpp#37]
We encountered a crash when calling `yapiInitAPI`. The crash happens at line 2952 of `Sources/yapi/yapi.c` because `yContext` is a null pointer. From my understanding of this function, `ctx` should be used at that line instead of `yContext`.

**Comment by srinsoz** [comment]
You are perfectly right. I will fix that monday. Thanks for the help.

**Comment by srinsoz** [comment]
Fixed. Thank you for your help.

**Comment by gppaille-vyv** [comment]
Great! Thanks for the responsiveness.
